name: A-飞鸡场

on:
  schedule:
    - cron: '15 23 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./-/C.TXT
        
      - name: '-' 
        run: python3 ./-/Fenji.py
        env:
            DJJ_TELE_COOKIE: ${{ secrets.DJJ_TELE_COOKIE }}
            XMLY_BARK_COOKIE: ${{ secrets.XMLY_BARK_COOKIE }}
            airplay_data: ${{ secrets.airplay_data }}
